name: deploy-infra
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev/hml/prod)'
        required: true
        default: 'dev'
      location:
        description: 'Azure region'
        required: true
        default: 'eastus'
      name:
        description: 'Base name (ex: fin)'
        required: true
        default: 'fin'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Create RG
        run: |
          az group create -n rg-${{ github.event.inputs.name }}-${{ github.event.inputs.env }}-core -l ${{ github.event.inputs.location }}
      - name: Deploy Bicep
        run: |
          az deployment group create \
            -g rg-${{ github.event.inputs.name }}-${{ github.event.inputs.env }}-core \
            -f infra/bicep/main.bicep \
            -p name=${{ github.event.inputs.name }} env=${{ github.event.inputs.env }} location=${{ github.event.inputs.location }} enablePrivateNetwork=false